blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # post views
    url(r'^$', views.post_list, name='post_list'),
    # url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'
        r'(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list,
        name='post_list_by_tag'),
]

polloblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
admin.autodiscover()

urlpatterns = i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('blog.urls', namespace='post_list',
                       app_name='post_list')),
    url(r'^blog/', include('blog.urls', namespace='blog',
                           app_name='blog')),
    url(r'^rosetta/', include('rosetta.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
from django.conf import settings
from django.utils.translation import gettext_lazy as _


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


def get_image_filename(instance, filename):
    title = instance.title
    slug = slugify(title)
    return "post_images/%s-%s" % (slug, filename)


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(_('title'), max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    image = models.ImageField(_('image'), upload_to=get_image_filename, blank=True)
    body = models.TextField(_('body'))
    publish = models.DateTimeField(_('publish'), default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(_('status'), max_length=10, choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'), self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Profile(models.Model):
    name = models.CharField(_('name'), max_length=100)
    occupation = models.CharField(_('occupation'), max_length=150)
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    date_of_birth = models.DateField(_('date of birth'), blank=True, null=True)
    photo = models.ImageField(_('photo'), upload_to='users/%Y/%m/%d', blank=True)
    description = models.TextField(_('description'))
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, \
    PageNotAnInteger
from django.views.generic import ListView
from .models import Post, Profile
from taggit.models import Tag


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    profiles = Profile.objects.get(pk=1)
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag,
                                                   'profiles': profiles})


def post_detail(request, year, month, day, post):
    profiles = Profile.objects.get(pk=1)
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post, 'profiles': profiles})

blog/templates/blog/aside.html
{% load i18n %}
{% load thumbnail %}
{% load blog_tags %}
        <div class="col-md-4 sidebar-gutter">
            <aside>
            <!-- sidebar-widget -->
            <div class="sidebar-widget">
                <h3 class="sidebar-title">{% trans "About Me" %}</h3>
                <div class="widget-container widget-about">
                    {% if profiles %}
                    <img src="{% thumbnail profiles.photo 720x740 crop="100%" %}" alt="">
                    {% else %}
                    {% endif %}
                    <h4>{{ profiles.name }}</h4>
                    <div class="author-title">{{ profiles.occupation }}</div>
                    <p>{{ profiles.description|markdown }}</p>
                </div>
            </div>

            <!-- total posts templatetag -->
            <div class="sidebar-widget">
                <h3 class="sidebar-title">{% trans "Total Posts" %}</h3>
                <div class="widget-container">
                    <article class="widget-post">
                        <div class="post-image">
                            <i class="fa fa-pencil-square fa-2x"></i>
                        </div>
                        <div class="post-body">
                             <h2>{% trans "Post so far in this blog" %}{% total_posts %}</h2>
                        </div>
                    </article>
                </div>
            </div>

            <!-- latest posts -->
            <div class="sidebar-widget">
                <h3 class="sidebar-title">{% trans "Latest Posts" %}</h3>
                {% show_latest_posts 3 %}
            </div>

            <!-- sidebar-widget -->
            <div class="sidebar-widget">
                <h3 class="sidebar-title">{% trans "Socials" %}</h3>
                <div class="widget-container">
                    <div class="widget-socials">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-google-plus"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-reddit"></i></a>
                    </div>
                </div>
            </div>
            <!-- sidebar-widget -->
            <div class="sidebar-widget">
                <h3 class="sidebar-title">{% trans "Categories" %}</h3>
                <div class="widget-container">
                    <ul>
                        <li><a href="#">Fashion</a></li>
                        <li><a href="#">Art</a></li>
                        <li><a href="#">Design</a></li>
                        <li><a href="#">Featured</a></li>
                        <li><a href="#">Graphics</a></li>
                        <li><a href="#">Peoples</a></li>
                        <li><a href="#">Uncategorized</a></li>
                    </ul>
                </div>
            </div>
            </aside>
        </div>

blog/templates/blog/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link href="{% static "css/jquery.bxslider.css" %}" rel="stylesheet">
        <link href="{% static "css/style.css" %}" rel="stylesheet">

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'blog:post_list' %}">Home</a></li>
                        <li><a href="#about">Lifestyle</a></li>
                        <li><a href="#contact">Travel</a></li>
                        <li><a href="#contact">Fashion</a></li>
                        <li><a href="about.html">About Me</a></li>
                        <li><a href="about.html">Contact</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <li>
                                <a href="/{{ language.code }}/"
                                        {% if language.code == LANGUAGE_CODE %} class="alert-success"{% endif %}>
                                {{ language.name_local }}
                                </a>
                            </li>
                        {% endfor %}
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-reddit"></i></a></li>
                    </ul>

                </div>
                <!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <header>
			    <a href=""><img src="images/logo.png"></a>
		    </header>

            {% block slider %}
            {% endblock %}

            {% block content %}

                {% block aside %}
                {% endblock %}

            {% endblock %}
        </div>
        {% block pagination %}
        {% endblock %}

		<footer class="footer">

			<div class="footer-socials">
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-instagram"></i></a>
				<a href="#"><i class="fa fa-google-plus"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-reddit"></i></a>
			</div>

			<div class="footer-bottom">
				<i class="fa fa-copyright"></i>{% trans "Copyright Pánfulo 2016. All rights reserved" %}.
			</div>
		</footer>


        <script src="{% static "js/jquery-1.12.2.min.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="{% static "js/jquery.bxslider.min.js" %}"></script>
        <script src="{% static "js/mooz.scripts.min.js" %}"></script>
    </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load i18n %}
{% load blog_tags %}
{% load thumbnail %}


{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<section>
    <div class="row">
        <div class="col-md-8">
            <article class="blog-post">
                {% if post.image %}
                <div class="blog-post-image">
                    <img src="{% thumbnail post.image 750x500 crop="100%" %}" alt="">
                </div>
                {% else %}
                {% endif %}
                <div class="blog-post-body">
                    <h2>{{ post.title }}</h2>
                    <div class="post-meta"><span>{% trans "Published by " %}<a href="#">{{ post.author }}</a>
                    </span>/<span><i class="fa fa-clock-o"></i>{{ post.publish }}</span>/
                        <span><i class="fa fa-comment-o"></i> <a href="#">343</a>
                    </span></div>
                    <div class="blog-post-text">
                        <p>{{ post.body|markdown }}</p>
                    </div>
                </div>
            </article>
        </div>
        {% block aside %}
            {% include "blog/aside.html" %}
        {% endblock %}
{% endblock %}
    </div>
</section>

blog/templates/blog/post/latest_posts.html
{% load thumbnail %}
    <div class="widget-container">
        {% for post in latest_posts %}
        <article class="widget-post">
         {% if post.image %}
            <div class="post-image">
                <a href="{{ post.get_absolute_url }}">
                    <img src="{% thumbnail post.image 90x60 crop="100%" %}" alt="">
                </a>
            </div>
            {% else %}
            <div class="post-image">
                <a href=""><img src="" alt=""></a>
            </div>
         {% endif %}
            <div class="post-body">
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                <div class="post-meta"><span>Published by <a href="#">{{ post.author }}</a>
                    </span>/<span><i class="fa fa-clock-o"></i>{{ post.publish }}</span>/
                        <span><i class="fa fa-comment-o"></i> <a href="#">343</a>
                </span></div>
            </div>
        </article>
        {% endfor %}
    </div>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load i18n %}
{% load blog_tags %}
{% load thumbnail %}

{% block title %}{% trans "Tecuan Soccer League"%}{% endblock %}

{% block slider %}
    <section class="main-slider">
        <ul class="bxslider">
        {% slider_latest_posts 3 %}
        </ul>
    </section>
{% endblock %}

{% block content %}
<section>
    <div class="row">
        <div class="col-md-8">
            {% if posts %}
            {% if tag %}
                <h2>{% trans "Posts tagged with " %}"{{ tag.name }}"</h2>
            {% endif %}
            {% for post in posts %}
            <article class="blog-post">
                {% if post.image %}
                <div class="blog-post-image">
                    <a href="{{ post.get_absolute_url }}">
                        <img src="{% thumbnail post.image 750x500 crop="100%" %}" alt="">
                    </a>
                </div>
                {% else %}
                <div class="blog-post-image">
                    <a href=""><img src="" alt=""></a>
                </div>
                {% endif %}

                <div class="blog-post-body">
                    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    <div class="post-meta"><span>Published by <a href="#">{{ post.author }}</a>
                    </span>/<span><i class="fa fa-clock-o"></i>{{ post.publish }}</span>/
                        <span><i class="fa fa-comment-o"></i> <a href="#">343</a>
                    </span></div>
                    <p>{{ post.body|markdown|truncatewords_html:30 }}</p>
                    <p class="post-meta">
                        <i class="fa fa-tags"></i> {% trans "Tags" %}:
                        {% for tag in post.tags.all %}
                            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                                {{ tag.name }}
                            </a>
                        {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>

                    <div class="read-more"><a href="{{ post.get_absolute_url }}">{% trans "Continue Reading" %}</a></div>
                </div>
            </article>
            {% endfor %}
            {% else %}
            <h1>No hay posts</h1>
            {% endif %}
        </div>
    {% block aside %}
        {% include "blog/aside.html" %}
    {% endblock %}
{% endblock %}
    </div>
</section>
{% block pagination %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/slider.html
{% load blog_tags %}
{% load thumbnail %}
    {% for post in slider_latest %}
    <li>
        <div class="slider-item"><img src="{% thumbnail post.image 1240x500 crop="100%" %}"
                                      title="{{ post.title }}" />
        <h2>
            <a href="{{ post.get_absolute_url }}" title="{{ post.title }}">{{ post.title }}</a>
        </h2>
        </div>
    </li>
    {% endfor %}

blog/templates/pagination.html
{% load i18n %}
    <div class="text-center">
        <nav>
            <ul class="pager">
                {% if page.has_previous %}
                    <li><a href="?page={{ page.previous_page_number }}">{% trans "Previous" %}</a></li>
                {% endif %}

                <span class="text-center">
                    {% trans "Page " %}{{ page.number }} {% trans "of" %} {{ page.paginator.num_pages }}.
                </span>

                {% if page.has_next %}
                    <li><a href="?page={{ page.next_page_number }}">{% trans "Next" %}</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>